import warnings
warnings.simplefilter("ignore")
import pandas as pd

not_exercise = pd.read_excel("./datas/reason_not_exercise.xlsx",header=1)
not_exercise

In [28]:
# 칼럼 (열) 리스트 작업
print(not_exercise.columns[1])
not_exercise.rename(columns={'구분별(1)':'대분류','구분별(2)':'분류'},inplace=True) # 칼럼 이름 변경
print(not_exercise.columns[1:3])
not_exercise.drop(columns='시점',inplace=True)
not_exercise

대분류
Index(['대분류', '분류'], dtype='object')

,대분류,분류,운동을 할 충분한 시간이 없어서,함께 운동을 할 사람이 없어서,운동을 할 만한 장소가 없어서,운동을 싫어해서,운동을 할 충분한 비용이 없어서,기타
0,서울시,소계,46.8,5.0,4.3,37.3,5.2,1.4
1,성별,남자,52.4,4.4,4.9,32.4,4.9,1.1
2,NaN,여자,42.5,5.6,3.9,41.0,5.4,1.7
3,연령별,10대,55.3,4.8,3.9,32.6,3.5,-
4,NaN,20대,46.0,4.2,4.5,38.8,6.4,0.1
5,NaN,30대,59.9,5.2,2.9,27.3,4.5,0.2
6,NaN,40대,54.1,3.9,2.9,35.5,3.3,0.4
7,NaN,50대,46.1,6.2,4.5,36.8,5.6,0.8
8,NaN,60대 이상,26.6,6.0,6.6,48.7,6.6,5.6
9,학력별,중졸 이하,24.7,6.2,4.8,48.6,7.3,8.5
10,NaN,고졸 이하,44.3,5.3,5.6,38.6,5.5,0.7
11,NaN,대졸 이하,53.1,4.7,3.3,34.0,4.6,0.3
12,NaN,대학원 이상,61.2,3.0,5.6,29.0,0.9,0.3
13,소득별,100만원 미만,10.7,8.4,9.9,50.7,9.4,10.9
14,NaN,100-200만원 미만,29.6,5.6,6.0,49.1,7.4,2.3
15,NaN,200-300만원 미만,42.8,7.3,3.9,39.5,5.1,1.4
16,NaN,300-400만원 미만,50.6,4.3,4.2,35.5,4.8,0.7
17,NaN,400-500만원 미만,48.0,4.6,3.3,38.7,5.3,0.2
18,NaN,500만원 이상,52.8,4.3,4.0,33.4,4.5,1
19,혼인상태별,기혼,48.7,4.5,4.1,37.3,4.6,0.7
20,NaN,미혼,50.2,4.9,4.0,35.1,5.6,0.2
21,NaN,이혼/사별/기타,31.5,7.2,5.7,42.4,6.4,6.9
22,지역대분류,도심권,53.8,3.8,7.2,28.3,4.0,2.9
23,NaN,동북권,44.5,3.5,4.1,40.6,5.5,1.8
24,NaN,서북권,50.7,6.6,5.1,31.4,5.3,0.9
25,NaN,서남권,47.1,6.7,4.7,35.9,4.8,0.8
26,NaN,동남권,46.3,4.7,3.1,38.9,5.4,1.5
27,지역소분류,종로구,62.2,0.4,9.4,25.9,2.1,-
28,NaN,중구,50.3,3.0,7.7,25.7,7.6,5.7
29,NaN,용산구,48.9,7.5,4.9,32.6,2.7,3.4
30,NaN,성동구,46.5,4.3,5.7,34.2,8.7,0.6
31,NaN,광진구,42.0,5.7,3.0,43.5,5.8,-
32,NaN,동대문구,44.5,4.5,2.7,41.9,6.2,0.1
33,NaN,중랑구,46.7,2.2,6.8,32.8,10.9,0.5
34,NaN,성북구,33.3,3.4,2.6,58.0,2.0,0.7
35,NaN,강북구,21.3,5.3,3.4,68.1,1.9,-
36,NaN,도봉구,52.0,3.2,6.2,30.8,7.6,0.3
37,NaN,노원구,56.3,1.6,2.7,30.1,1.9,7.4
38,NaN,은평구,42.7,8.8,7.3,34.3,6.4,0.5
39,NaN,서대문구,69.8,0.8,1.2,21.9,5.3,1
40,NaN,마포구,46.6,8.1,4.7,35.8,3.2,1.5
41,NaN,양천구,66.2,5.7,5.9,17.9,4.1,0.1
42,NaN,강서구,38.5,3.8,1.9,50.5,4.3,1
43,NaN,구로구,45.3,5.7,5.8,39.0,2.9,1.3
44,NaN,금천구,53.6,2.4,2.3,37.6,2.3,1.7
45,NaN,영등포구,50.2,6.7,3.8,33.9,5.4,-
46,NaN,동작구,39.1,13.9,8.4,31.1,7.6,-
47,NaN,관악구,44.4,8.8,5.5,34.2,6.1,1
48,NaN,서초구,49.9,4.3,4.1,36.6,3.3,1.8
49,NaN,강남구,40.7,4.2,2.0,46.4,5.2,1.6
50,NaN,송파구,47.6,5.0,2.3,39.4,4.8,1
51,NaN,강동구,47.0,5.2,4.8,32.4,8.4,2.3

In [29]:
# not_exercise
not_exercise.drop(index=range(22, 52), inplace=True)#22~51행까지 삭제
not_exercise

,대분류,분류,운동을 할 충분한 시간이 없어서,함께 운동을 할 사람이 없어서,운동을 할 만한 장소가 없어서,운동을 싫어해서,운동을 할 충분한 비용이 없어서,기타
0,서울시,소계,46.8,5.0,4.3,37.3,5.2,1.4
1,성별,남자,52.4,4.4,4.9,32.4,4.9,1.1
2,NaN,여자,42.5,5.6,3.9,41.0,5.4,1.7
3,연령별,10대,55.3,4.8,3.9,32.6,3.5,-
4,NaN,20대,46.0,4.2,4.5,38.8,6.4,0.1
5,NaN,30대,59.9,5.2,2.9,27.3,4.5,0.2
6,NaN,40대,54.1,3.9,2.9,35.5,3.3,0.4
7,NaN,50대,46.1,6.2,4.5,36.8,5.6,0.8
8,NaN,60대 이상,26.6,6.0,6.6,48.7,6.6,5.6
9,학력별,중졸 이하,24.7,6.2,4.8,48.6,7.3,8.5
10,NaN,고졸 이하,44.3,5.3,5.6,38.6,5.5,0.7
11,NaN,대졸 이하,53.1,4.7,3.3,34.0,4.6,0.3
12,NaN,대학원 이상,61.2,3.0,5.6,29.0,0.9,0.3
13,소득별,100만원 미만,10.7,8.4,9.9,50.7,9.4,10.9
14,NaN,100-200만원 미만,29.6,5.6,6.0,49.1,7.4,2.3
15,NaN,200-300만원 미만,42.8,7.3,3.9,39.5,5.1,1.4
16,NaN,300-400만원 미만,50.6,4.3,4.2,35.5,4.8,0.7
17,NaN,400-500만원 미만,48.0,4.6,3.3,38.7,5.3,0.2
18,NaN,500만원 이상,52.8,4.3,4.0,33.4,4.5,1
19,혼인상태별,기혼,48.7,4.5,4.1,37.3,4.6,0.7
20,NaN,미혼,50.2,4.9,4.0,35.1,5.6,0.2
21,NaN,이혼/사별/기타,31.5,7.2,5.7,42.4,6.4,6.9

In [33]:
not_exercise.loc[2, "대분류"] = "성별" # 2행의 NaN을 찾아 성별로 변경함
not_exercise.loc[2]
not_ex_sex = not_exercise[not_exercise['대분류'] == '성별'].copy() # 깊은 복사
not_ex_sex

,대분류,분류,운동을 할 충분한 시간이 없어서,함께 운동을 할 사람이 없어서,운동을 할 만한 장소가 없어서,운동을 싫어해서,운동을 할 충분한 비용이 없어서,기타
1,성별,남자,52.4,4.4,4.9,32.4,4.9,1.1
2,성별,여자,42.5,5.6,3.9,41.0,5.4,1.7

In [34]:
not_ex_sex.drop(columns="대분류",inplace=True)
not_ex_sex

,분류,운동을 할 충분한 시간이 없어서,함께 운동을 할 사람이 없어서,운동을 할 만한 장소가 없어서,운동을 싫어해서,운동을 할 충분한 비용이 없어서,기타
1,남자,52.4,4.4,4.9,32.4,4.9,1.1
2,여자,42.5,5.6,3.9,41.0,5.4,1.7

In [35]:
import matplotlib as plt

fig, ax = plt.subprocess(1, 2, figsiz(16,8))#1 행 2열

plt.rc("font",familly="Malgun Gothic")
not_ex_sex['운동을 할 충분한 시간이 없어서'].plot.ple(ax=ax[0],autopct="%1.f%%", startangle=90)
ax[0].set_title('운동을 할 충분한 시간이 없어서')

NameError: name 'figsiz' is not defined